### ISSUE TITLE
pay attention to your cairo version（ official version is2.0）注意你安装用的cairo版本，官方已经更新到2.0了，语法许多不一样

### ISSUE THREAD

**Issue by lrqstudy** [WTFAcademy/WTF-Cairo#24]
https://github.com/starkware-libs/cairo/tree/main
官方的cairo版本一件到2.0 了，但是wtf的教程是1.0  
starknet 官方更新太快了，我根据wtf教程发现cairo我用的都是2.0版本了，很多语法跟1.0版本不一样，估计其他人也会有这个问题
因此提了个issue

**Comment by AmazingAng** [comment]
是的，我们接到了cairo更新版本的通知，近期我们会更新一波，敬请期待。

**Comment by AmazingAng** [comment]
教程已更新到cairo 2.2
