### ISSUE TITLE
scarb.toml 文件中内容有缺失，build 会失败

### ISSUE THREAD

**Issue by neal-zhu** [WTFAcademy/WTF-Cairo#27]
`[dependencies]
starknet = "2.2.0"

[[target.starknet-contract]]

casm = true

`
应该在文档中说明，在 toml 文件中添加以上内容

**Comment by AmazingAng** [comment]
好的 提个pr吧

**Comment by buttonwild** [comment]
修复第一讲

**Comment by buttonwild** [comment]
#45
